<?php

namespace AppBundle\Repository;

/**
 * ureferencesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UreferencesRepository extends \Doctrine\ORM\EntityRepository
{
}
